# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(597, 538)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(597, 538))
        MainWindow.setMaximumSize(QtCore.QSize(597, 538))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblOptions = QtGui.QLabel(self.centralwidget)
        self.lblOptions.setObjectName(_fromUtf8("lblOptions"))
        self.verticalLayout_2.addWidget(self.lblOptions)
        self.checkBoxComputer = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxComputer.setChecked(True)
        self.checkBoxComputer.setObjectName(_fromUtf8("checkBoxComputer"))
        self.verticalLayout_2.addWidget(self.checkBoxComputer)
        self.btnOpIniciar = QtGui.QPushButton(self.centralwidget)
        self.btnOpIniciar.setObjectName(_fromUtf8("btnOpIniciar"))
        self.verticalLayout_2.addWidget(self.btnOpIniciar)
        self.checkBoxVoiceCmd = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxVoiceCmd.setObjectName(_fromUtf8("checkBoxVoiceCmd"))
        self.verticalLayout_2.addWidget(self.checkBoxVoiceCmd)
        self.checkBoxUciSan = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxUciSan.setObjectName(_fromUtf8("checkBoxUciSan"))
        self.verticalLayout_2.addWidget(self.checkBoxUciSan)
        self.groupBoxMover = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxMover.setObjectName(_fromUtf8("groupBoxMover"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxMover)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupBoxMover)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBoxMoveFrom = QtGui.QComboBox(self.groupBoxMover)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMoveFrom.sizePolicy().hasHeightForWidth())
        self.comboBoxMoveFrom.setSizePolicy(sizePolicy)
        self.comboBoxMoveFrom.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxMoveFrom.setObjectName(_fromUtf8("comboBoxMoveFrom"))
        self.horizontalLayout_4.addWidget(self.comboBoxMoveFrom)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.groupBoxMover)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.comboBoxMoveTo = QtGui.QComboBox(self.groupBoxMover)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxMoveTo.sizePolicy().hasHeightForWidth())
        self.comboBoxMoveTo.setSizePolicy(sizePolicy)
        self.comboBoxMoveTo.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxMoveTo.setObjectName(_fromUtf8("comboBoxMoveTo"))
        self.horizontalLayout_5.addWidget(self.comboBoxMoveTo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.pushButtonMove = QtGui.QPushButton(self.groupBoxMover)
        self.pushButtonMove.setObjectName(_fromUtf8("pushButtonMove"))
        self.verticalLayout_4.addWidget(self.pushButtonMove)
        self.verticalLayout_2.addWidget(self.groupBoxMover)
        self.btn_computer_move = QtGui.QPushButton(self.centralwidget)
        self.btn_computer_move.setObjectName(_fromUtf8("btn_computer_move"))
        self.verticalLayout_2.addWidget(self.btn_computer_move)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_7.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.labelStatus = QtGui.QLabel(self.centralwidget)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.verticalLayout.addWidget(self.labelStatus)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Xadrez de bruxo", None))
        self.lblOptions.setText(_translate("MainWindow", "Opções:", None))
        self.checkBoxComputer.setText(_translate("MainWindow", "Computer", None))
        self.btnOpIniciar.setText(_translate("MainWindow", "Iniciar", None))
        self.checkBoxVoiceCmd.setText(_translate("MainWindow", "Comando de Voz", None))
        self.checkBoxUciSan.setText(_translate("MainWindow", "Uci/San", None))
        self.groupBoxMover.setTitle(_translate("MainWindow", "Mover", None))
        self.label_2.setText(_translate("MainWindow", "De:", None))
        self.label.setText(_translate("MainWindow", "Para:", None))
        self.pushButtonMove.setText(_translate("MainWindow", "Mover", None))
        self.btn_computer_move.setText(_translate("MainWindow", "ComputerMove", None))
        self.label_3.setText(_translate("MainWindow", "Here will be the board", None))
        self.labelStatus.setText(_translate("MainWindow", "Status:", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))

